name: Node Production Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Installation Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Installation des dépendances
        run: npm install

      - name: Vérification application
        run: node index.js